import type { NextPage } from "next";
import Head from "next/head";
import Computer from '../components/Computer';
import GitHubIcon from '../components/GitHubIcon';
import LinkedInIcon from '../components/LinkedInIcon';

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Fischer Davis</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="lg:text-2xl sm:text-xl flex justify-center align-middle pt-2 lg:pt-32">
        <div className="lg:flex lg:gap-4">
          <div className="lg:w-[800px]">
            <h1 className="font-bold font-mono pl-4 italic mb-4 lg:mb-10">Hi, I'm Fischer Davis</h1>
            <p className="font-mono pl-6 pr-6 lg:pl-12">
                I'm a fullstack developer that enjoys building exceptional digital experiences.
                I currently work in the Law software industry designing, developing, and maintaining software that is used by some of the largest firms in the US.
            </p>
            <div className="pt-10 flex gap-6 justify-center">
              <div className="w-[50px] h-[50px] hover:scale-125">
                <GitHubIcon />
              </div>
              <div className="w-[50px] h-[50px] hover:scale-125">
                <LinkedInIcon />
              </div>
            </div>
          </div>
          <Computer />
        </div>
      </div>
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
